### ISSUE TITLE
Support new account creation by user account request

### ISSUE THREAD

**Issue by ribose-jeffreylau** [paneron/registry-kit#8]
Provide a way to "request user account", which sends an email to the account manager, who makes the decision as to who is able to submit proposals.

from discussion with @maccraymer

**Comment by strogonoff** [comment]
I think this was explicitly not required. We don’t want a feature that allows users to request accounts here. Accounts can be requested separately (e.g., via a Google form or something similar), which could send an email to _register owner_ (or manager?), who could then choose to create an account. However, this is out of scope of this repository and others.

**Comment by maccraymer** [comment]
I agree. We don't really need functionality for the general public to submit requests for user accounts. This feature is present with the current registry and *all* such requests were not appropriate and rejected. I have simply been creating accounts as needed (mainly for Control Body members, many of whom have submitted proposals as authoritative sources).
-Mike
